//
// Copyright (C) 2006-2009  by the original authors of Galaxy
// and all its contributors ("Galaxy.org").
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

/*!
  \file version.cpp
  \ingroup Core
  \brief This file contains
  - class Core::Version implemtation
  <strike>This file is generated by software.</strike>
  \version 0.0.1
  \author Cheng Liang <changliang.soft@gmail.com>
  \date 2009-12-14 Created.
  \date 2010-5-16 vergen updated.
 */

#include <QString>

#include "version.h"

/*!
  \class Core::Version version.h
  \brief Version information of PicWorks.
  \version 0.0.1 SVN
  \version 0.0.2 2010-3-3 SCM changed to non-SCM-related.
  \author Cheng Liang <chengliang.soft@gmail.com>
  \date 2009-12-14 Created.
  \date 2010-5-16
  \date 2010-5-30 import static const fields
 */

/*!
  \brief URL of workcopy.
  Workcopy is often the source repo of the application.
 */
const QString Core::Version::workcopyUrl = QString("http://picworks.hg.sourceforge.net:8000/hgroot/picworks/picworks");

/*!
  \brief Major version number.
  Major version number increased when lots of features updated.
 */
const QString Core::Version::major = QString("0");

/*!
  \brief Minor version number.
  Minor version number increased when some feature updated 
  but the main code is almost the same.
 */
const QString Core::Version::minor = QString("0");

/*!
  \brief Revision number.
  Revision number increased when another version released.
 */
const QString Core::Version::revision = QString("20100609");

/*!
  \brief Build version number.
  Build version number will be increase when rebuild needed.
  Often with libraries or execute update.
 */
const QString Core::Version::build = QString("1");

/*!
  \brief Build date in short format as YYYY-MM-DD.
  Build date is the date on which build.
 */
const QString Core::Version::buildDate = QString("2010-6-9");
