//
// Copyright (C) 2006-2009  by the original authors of Galaxy
// and all its contributors ("Galaxy.org").
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

/*!
  \file version.cpp
  \ingroup Core
  \brief This file contains
  - class Core::VersionInfo implemtation
  <strike>This file is generated by SubWCRev.</strike>
  \version 0.0.1
  \author Cheng Liang <changliang.soft@gmail.com>
  \date 2009-12-14 Created.
 */

#include "version.h"

/*!
  \class Core::VersionInfo version.h
  \brief Version information of PicWorks.
  \version 0.0.1 SVN
  \version 0.0.2 2010-3-3 SCM changed to non-SCM-related.
  \author Cheng Liang <chengliang.soft@gmail.com>
  \date 2009-12-14 Created.
 */

/*!
  \fn QString Core::VersionInfo::buildDate()
  \brief Build date in short format as YYYY-MM-DD.
  \return workcopy build date

  \fn QString Core::VersionInfo::url()
  \brief PicWorks version control system URL.
  \return URL of version control system

  \fn QString Core::VersionInfo::major()
  \brief Major version number.
  \return major version number

  \fn QString Core::VersionInfo::minor()
  \brief Minor version number.
  \return minor version number

  \fn QString Core::VersionInfo::revision()
  \brief Revision number.
  \return the rivision number

  \fn QString Core::VersionInfo::build()
  \brief Build version number.
  \return build version number
 */

Core::VersionInfo::VersionInfo()
    : wcURL("http://picworks.hg.sourceforge.net:8000/hgroot/picworks/picworks"),
      bDate("2010-5-3"),
      rivi("0"),
      ma("0"),
      mi("0"),
      bu("1")
{

}
